(ns wagoe.generated-deps-parity-test
  "Can a generated project switch on every module its config can name?

   `deps.edn.tmpl` says so in as many words — \"the modules a fresh project can
   switch on by editing config.edn alone\" — and ten of them were not in it.
   Activating one failed at boot on a classpath error naming a library the
   reader had never chosen (BOU-420), the shape BOU-414 fixed for `bb setup`.

   Read from the template rather than from a generated project: this is about
   what `wagoe new` writes, and generating one per test run costs a network."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [wagoe.platform.shell.modules :as modules]))

(def ^:private add-first
  "Libraries a generated project deliberately does not carry, and why.

   `devtools` is the only entry the framework itself calls legitimately absent
   — `optional-modules` names it, and its wiring is skipped rather than fatal.
   It ships in the `:repl` alias. Anything else here needs the same standing:
   a module whose absence the platform tolerates."
  {"devtools" "dev-only; ships in the :repl alias, and :wagoe/dev-error-enricher is the one key platform skips when its library is missing"})

(defn- template-deps
  "Library names in the template's top-level `:deps`."
  []
  (let [text (slurp (io/file "libs/wagoe-cli/resources/wagoe/cli/templates/deps.edn.tmpl"))
        top  (subs text (str/index-of text ":deps") (str/index-of text ":aliases"))]
    (set (map second (re-seq #"com\.wagoe/wagoe-([a-z0-9-]+)" top)))))

(deftest ^:unit every-switch-on-able-module-is-in-the-generated-deps
  (let [in-deps  (template-deps)
        required (set (vals modules/framework-modules))]

    (testing "both sides were read — otherwise this passes vacuously"
      (is (< 15 (count in-deps)) "the template's :deps did not parse")
      (is (< 15 (count required)) "framework-modules did not load"))

    (testing "every module the config can activate resolves from the generated deps"
      (let [missing (remove #(or (contains? in-deps %) (contains? add-first %)) required)]
        (is (empty? missing)
            (str "a project generated by `wagoe new` cannot switch these on: "
                 (pr-str (sort missing))
                 " — add them to deps.edn.tmpl with a {{<lib>-version}} placeholder,"
                 " or record why they are add-first"))))

    (testing "and nothing is excused that no longer needs excusing"
      (doseq [[lib why] add-first]
        (is (contains? required lib)
            (str lib " is not a framework module any more — drop it from add-first (" why ")"))
        (is (not (contains? in-deps lib))
            (str lib " is in the generated deps and also listed as add-first"))))))

(deftest ^:unit every-template-dependency-has-a-version-to-substitute
  ;; A coordinate whose `{{x-version}}` nobody fills renders literally, and the
  ;; project fails on an unresolvable version rather than a missing library.
  (let [text (slurp (io/file "libs/wagoe-cli/resources/wagoe/cli/templates/deps.edn.tmpl"))
        subs (slurp (io/file "libs/wagoe-cli/src/wagoe/cli/new.clj"))
        placeholders (set (map second (re-seq #"\{\{([a-z0-9-]+)-version\}\}" text)))]
    (is (seq placeholders))
    (doseq [p placeholders]
      (is (str/includes? subs (str ":" p "-version"))
          (str "deps.edn.tmpl uses {{" p "-version}} and new.clj substitutes no such key")))))
