(ns boundary.reports.shell.adapters.word-test
  "Integration tests for the Apache POI XWPF Word adapter.
   Generates real DOCX bytes — verifies ZIP magic bytes (DOCX = ZIP container)."
  (:require [boundary.reports.shell.adapters.word :as sut]
            [boundary.reports.ports :as ports]
            [clojure.test :refer [deftest is testing]]))

;; =============================================================================
;; Helpers
;; =============================================================================

(def ^:private sample-sections-report
  {:id       :word-test-sections
   :type     :word
   :filename "test-output.docx"
   :sections [{:type    :header
               :content "Quarterly Report"}
              {:type    :paragraph
               :content "This report covers Q1 2026 sales figures."}
              {:type    :table
               :columns [{:key :product  :label "Product"}
                         {:key :quantity :label "Qty"     :format :number}
                         {:key :revenue  :label "Revenue" :format :currency}]}
              {:type :spacer}
              {:type    :footer
               :content "Generated by boundary-reports"}]})

(def ^:private sample-data
  [{:product "Alpha"  :quantity 10 :revenue 199.90}
   {:product "Beta"   :quantity 5  :revenue 499.50}
   {:product "Gamma"  :quantity 3  :revenue  13.47}])

;; =============================================================================
;; ZIP / DOCX magic bytes helper
;; =============================================================================

(defn- docx-magic? [^bytes bytes]
  ;; DOCX is a ZIP file. ZIP magic: 50 4B 03 04
  (and (>= (count bytes) 4)
       (= (aget bytes 0) (byte 0x50))  ; P
       (= (aget bytes 1) (byte 0x4B))  ; K
       (= (aget bytes 2) (byte 0x03))
       (= (aget bytes 3) (byte 0x04))))

;; =============================================================================
;; Tests
;; =============================================================================

(deftest word-magic-bytes-test
  ^:integration
  (testing "sections-based report produces valid DOCX bytes"
    (let [gen    (sut/create-word-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (some? (:bytes result)))
      (is (pos? (count (:bytes result))))
      (is (docx-magic? (:bytes result))))))

(deftest word-filename-default-test
  ^:integration
  (testing "filename defaults to <id>.docx when not specified"
    (let [gen  (sut/create-word-generator)
          defn {:id       :my-word-report
                :type     :word
                :sections [{:type    :header
                            :content "Hello"}]}
          result (ports/generate! gen defn [] {})]
      (is (= "my-word-report.docx" (:filename result)))))
  (testing "explicit filename is used"
    (let [gen    (sut/create-word-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (= "test-output.docx" (:filename result))))))

(deftest word-supported-type-test
  (testing "supported-type? returns true for :word"
    (is (ports/supported-type? (sut/create-word-generator) :word)))
  (testing "supported-type? returns false for :pdf"
    (is (not (ports/supported-type? (sut/create-word-generator) :pdf)))))

(deftest word-type-in-output-test
  ^:integration
  (testing ":type is :word in output"
    (let [gen    (sut/create-word-generator)
          result (ports/generate! gen sample-sections-report sample-data {})]
      (is (= :word (:type result))))))

(deftest word-empty-sections-test
  ^:integration
  (testing "report with no sections still produces valid DOCX bytes"
    (let [gen    (sut/create-word-generator)
          report {:id   :empty-word
                  :type :word}
          result (ports/generate! gen report [] {})]
      (is (docx-magic? (:bytes result))))))
