#!/usr/bin/env bb
;; libs/tools/src/boundary/tools/quickstart.clj
;;
;; Quickstart — one command from clone to running app.
;;
;; Usage (via bb.edn task):
;;   bb quickstart                  # Interactive quickstart
;;   bb quickstart --preset minimal # Non-interactive with minimal preset

(ns boundary.tools.quickstart
  (:require [boundary.tools.ansi :refer [bold green red dim]]
            [babashka.process :as process]
            [clojure.java.io :as io]
            [clojure.string :as str]))

;; =============================================================================
;; Presets — named onboarding profiles mapping to concrete setup flags
;; =============================================================================

(def presets
  {"minimal"  {:database "h2"         :description "H2 in-memory, no extras"}
   "standard" {:database "postgresql" :description "PostgreSQL, recommended for production"}
   "sqlite"   {:database "sqlite"     :description "SQLite file-based, zero-config"}
   "mysql"    {:database "mysql"      :description "MySQL/MariaDB"}})

(defn- resolve-preset
  "Resolve a preset name to setup flags. Returns nil if unknown."
  [preset-name]
  (get presets preset-name))

;; =============================================================================
;; Config injection — adds Integrant key to config.edn :active section
;; =============================================================================

(def ^:private sample-config-snippet
  "Integrant config snippet for the sample tasks module."
  (str "\n  ;; Tasks module (generated by quickstart)\n"
       "  :boundary/tasks\n"
       "  {:enabled? true\n"
       "   :base-path \"/api/tasks\"}\n"))

(defn- inject-module-config
  "Inject the sample module Integrant config into a config.edn file.
   Inserts before the closing brace of the :active section.
   Returns true if injection succeeded."
  [config-path]
  (let [f (io/file config-path)]
    (when (.exists f)
      (let [text (slurp f)]
        (if (str/includes? text ":boundary/tasks")
          true ;; already present
          ;; Find :inactive and insert before it
          (let [idx (str/index-of text ":inactive")]
            (if idx
              ;; Insert before the closing brace of :active (the } just before :inactive)
              (let [brace-idx (str/last-index-of text "}" idx)]
                (if brace-idx
                  (let [new-text (str (subs text 0 brace-idx)
                                      sample-config-snippet
                                      (subs text brace-idx))]
                    (spit config-path new-text)
                    true)
                  false))
              false)))))))

(defn inject-sample-module-config
  "Inject the sample tasks module config into dev and test config.edn files."
  []
  (let [root    (System/getProperty "user.dir")
        dev-ok  (inject-module-config (str root "/resources/conf/dev/config.edn"))
        test-ok (inject-module-config (str root "/resources/conf/test/config.edn"))]
    (and dev-ok test-ok)))

;; =============================================================================
;; Step runner
;; =============================================================================

(defn- run-step
  "Run a named step. Returns true if successful."
  [step-num total description cmd & {:keys [continue?]}]
  (println)
  (println (bold (str "[" step-num "/" total "] " description)))
  (println (dim (str "  $ " (str/join " " cmd))))
  (let [result (apply process/shell {:continue true} cmd)
        ok?    (zero? (:exit result))]
    (if ok?
      (println (green "  Done"))
      (do (println (red "  Failed"))
          (when-not continue?
            (println (red "\nQuickstart aborted. Fix the issue above and re-run bb quickstart."))
            (System/exit 1))))
    ok?))

;; =============================================================================
;; Main flow
;; =============================================================================

(defn- print-banner []
  (println)
  (println (bold "━━━ Boundary Quickstart ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
  (println)
  (println "  This will set up a complete Boundary development environment.")
  (println "  Steps: check environment, configure, scaffold, migrate, start.")
  (println))

(defn- print-success []
  (println)
  (println (green (bold "━━━ Quickstart Complete ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")))
  (println)
  (println (green "  Your Boundary project is configured and ready to start!"))
  (println)
  (println "  Next steps:")
  (println "    1. Start the REPL:  " (bold "clojure -M:repl-clj"))
  (println "    2. In the REPL:     " (bold "(go)"))
  (println "    3. The startup dashboard will show you the URLs and ports")
  (println)
  (println "  Useful commands:")
  (println "    " (bold "bb scaffold") "   — create more modules")
  (println "    " (bold "bb guide") "      — contextual help and guidance")
  (println "    " (bold "(status)") "      — in the REPL, show URLs and health")
  (println "    " (bold "(commands)") "    — in the REPL, see all helpers")
  (println))

(defn -main [& args]
  (let [preset-idx (.indexOf (vec args) "--preset")
        preset-name (when (and (>= preset-idx 0) (< (inc preset-idx) (count args)))
                      (nth args (inc preset-idx)))
        preset      (when preset-name (resolve-preset preset-name))]
    (when (and preset-name (not preset))
      (println (red (str "Unknown preset: " preset-name)))
      (println (dim (str "Available presets: " (str/join ", " (sort (keys presets))))))
      (System/exit 1))

    (print-banner)

    ;; Step 1: Check environment prerequisites (critical — abort on failure)
    (run-step 1 8 "Checking development environment"
              ["bb" "doctor:env" "--ci"])

    ;; Step 2: Run setup
    (if preset
      (do (println (dim (str "\n  Using preset: " preset-name " (" (:description preset) ")")))
          (run-step 2 8 "Running configuration setup"
                    ["bb" "setup" "--database" (:database preset)]))
      (run-step 2 8 "Running configuration setup"
                ["bb" "setup"]))

    ;; Step 3: Validate configuration (critical — abort on failure)
    (run-step 3 8 "Validating configuration"
              ["bb" "doctor" "--ci"])

    ;; Step 4: Scaffold and integrate a sample module (non-critical — continue on failure)
    (let [scaffolded? (run-step 4 8 "Scaffolding sample module"
                                ["bb" "scaffold" "generate" "tasks" "title:string" "done:boolean"]
                                :continue? true)]
      (when scaffolded?
        (run-step 5 8 "Integrating sample module into project"
                  ["bb" "scaffold" "integrate" "tasks"]
                  :continue? true)
        ;; Step 6: Activate module in config — the part integrate leaves manual
        (println)
        (println (bold (str "[6/8] Activating sample module in config")))
        (if (inject-sample-module-config)
          (println (green "  Done"))
          (println (dim "  Skipped — could not inject config (add :boundary/tasks manually)")))))

    ;; Step 7: Run migrations (critical — abort on failure)
    (run-step 7 8 "Running database migrations"
              ["bb" "migrate" "up"])

    ;; Step 8: Verify project structure
    (run-step 8 8 "Verifying project structure"
              ["bb" "smoke-check"])

    (print-success)))

;; Run when executed directly
(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
